packages:
  - packages/*
  - docs

catalog:
  '@dotenvx/dotenvx': ^1.47.3
  '@opentelemetry/api': ^1.9.0
  '@opentelemetry/resources': ^1.25.1
  '@opentelemetry/sdk-metrics': ^1.25.1
  '@opentelemetry/sdk-trace-base': ^1.25.1
  '@opentelemetry/semantic-conventions': ^1.25.1
  tsdown: ^0.12.7
  typescript: 5.8.3

engineStrict: true

nodeVersion: 20.18.0

shellEmulator: true
