version: "3.8"

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: upyo-mailpit
    ports:
    - "1025:1025"  # SMTP port
    - "8025:8025"  # Web interface port
    environment:
    - MP_SMTP_AUTH_ACCEPT_ANY=1
    - MP_SMTP_AUTH_ALLOW_INSECURE=1
    volumes:
    - mailpit-data:/data
    restart: unless-stopped
    healthcheck:
      test:
      - CMD,
      - wget
      - --quiet
      - --tries=1
      - --spider
      - http://localhost:8025/api/v1/info
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mailpit-data:
