name: main
on: [push, pull_request]

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: latest
        run_install: true
    - uses: actions/setup-node@v4
      with:
        node-version: latest
    - run: pnpm run -r test

  test-deno:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - run: deno task test --coverage --junit-path=junit.xml
    - if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: junit.xml
    - uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/lcov.info

  test-bun:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: latest
        run_install: true
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - run: pnpm run -r test:bun
