name: main
on: [push, pull_request]

jobs:
  test-node:
    runs-on: ubuntu-latest
    services:
      mailpit:
        image: axllent/mailpit:latest
        ports:
        - 1025:1025  # SMTP port
        - 8025:8025  # Web interface port
        env:
          MP_SMTP_AUTH_ACCEPT_ANY: "1"
          MP_SMTP_AUTH_ALLOW_INSECURE: "1"
        options: >-
          --health-cmd="wget --quiet --tries=1 --spider http://localhost:8025/api/v1/info"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=3
          --health-start-period=40s
    env:
      MAILPIT_SMTP_HOST: localhost
      MAILPIT_SMTP_PORT: 1025
      MAILPIT_SMTP_SECURE: "false"
      MAILPIT_API_URL: http://localhost:8025
      MAILGUN_KEY: ${{ secrets.MAILGUN_KEY }}
      MAILGUN_FROM: ${{ secrets.MAILGUN_FROM }}
      MAILGUN_TO: ${{ secrets.MAILGUN_TO }}
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      MAILGUN_REGION: ${{ secrets.MAILGUN_REGION }}
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: latest
        run_install: true
    - uses: actions/setup-node@v4
      with:
        node-version: latest
    - run: pnpm run -r test

  test-deno:
    runs-on: ubuntu-latest
    services:
      mailpit:
        image: axllent/mailpit:latest
        ports:
        - 1025:1025  # SMTP port
        - 8025:8025  # Web interface port
        env:
          MP_SMTP_AUTH_ACCEPT_ANY: "1"
          MP_SMTP_AUTH_ALLOW_INSECURE: "1"
        options: >-
          --health-cmd="wget --quiet --tries=1 --spider http://localhost:8025/api/v1/info"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=3
          --health-start-period=40s
    env:
      MAILPIT_SMTP_HOST: localhost
      MAILPIT_SMTP_PORT: 1025
      MAILPIT_SMTP_SECURE: "false"
      MAILPIT_API_URL: http://localhost:8025
      MAILGUN_KEY: ${{ secrets.MAILGUN_KEY }}
      MAILGUN_FROM: ${{ secrets.MAILGUN_FROM }}
      MAILGUN_TO: ${{ secrets.MAILGUN_TO }}
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      MAILGUN_REGION: ${{ secrets.MAILGUN_REGION }}
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - run: deno task test --coverage --junit-path=junit.xml
    - if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: junit.xml
    - uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/lcov.info

  test-bun:
    runs-on: ubuntu-latest
    services:
      mailpit:
        image: axllent/mailpit:latest
        ports:
        - 1025:1025  # SMTP port
        - 8025:8025  # Web interface port
        env:
          MP_SMTP_AUTH_ACCEPT_ANY: "1"
          MP_SMTP_AUTH_ALLOW_INSECURE: "1"
        options: >-
          --health-cmd="wget --quiet --tries=1 --spider http://localhost:8025/api/v1/info"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=3
          --health-start-period=40s
    env:
      MAILPIT_SMTP_HOST: localhost
      MAILPIT_SMTP_PORT: 1025
      MAILPIT_SMTP_SECURE: "false"
      MAILPIT_API_URL: http://localhost:8025
      MAILGUN_KEY: ${{ secrets.MAILGUN_KEY }}
      MAILGUN_FROM: ${{ secrets.MAILGUN_FROM }}
      MAILGUN_TO: ${{ secrets.MAILGUN_TO }}
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      MAILGUN_REGION: ${{ secrets.MAILGUN_REGION }}
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: latest
        run_install: true
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - run: pnpm run -r test:bun

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - run: deno task check

  publish:
    if: github.event_name == 'push'
    needs: [test-node, test-deno, test-bun, check]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - uses: pnpm/action-setup@v4
      with:
        version: latest
        run_install: true
    - run: |
        set -ex
        if [[ "$GITHUB_REF_TYPE" == tag ]]; then
          deno task check-versions
          [[ "$(jq -r '.version' packages/core/deno.json)" == "$GITHUB_REF_NAME" ]]
        else
          jq \
            --arg build "$GITHUB_RUN_NUMBER" \
            --arg commit "${GITHUB_SHA::8}" \
            '.version = .version + "-dev." + $build + "+" + $commit' \
            packages/core/deno.json > /tmp/deno.json
          mv /tmp/deno.json packages/core/deno.json
          deno task check-versions --fix
        fi
    - run: |
        set -ex
        deno publish --allow-dirty
        pnpm config set //registry.npmjs.org/:_authToken "$NPM_AUTH_TOKEN"
        if [[ "$GITHUB_REF_TYPE" == tag ]]; then
          pnpm publish \
            --recursive \
            --no-git-checks \
            --access public \
            --force
        else
          pnpm publish \
            --recursive \
            --no-git-checks \
            --access public \
            --force \
            --tag dev
        fi
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        NPM_CONFIG_PROVENANCE: "true"
